name: Setup Node and install dependencies
description: Setup Node.js with npm cache and install dependencies.
inputs:
  node-version-file:
    description: Path to the Node version file.
    required: true
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: npm
    - name: Install dependencies
      run: npm ci
      shell: bash
